package consts;

public interface Consts {
    int COLOR_RED = 16711680;
    int COLOR_GREEN = 65280;
    int SCANWORDFRAME_GRIDHEIGHT = 1;
    int SCANWORDFRAME_GRIDHWIDTH = 1;
    int SCANWORDFRAME_FIELDS_MAXLENGTH = 1;
    int SCANWORDFRAME_FIELDS_WIDTH = 50;
    int SCANWORDFRAME_FIELDS_HEIGHT = 30;
    int SCANWORDFRAME_FIELDS_FONTSIZE = 16;
    int END_FRAME_GRIDWIDTH = 2;
    int END_FRAME_GRIDHEIGHT = 1;
    int END_FRAME_FONTSIZE = 25;
    int END_FRAME_INSETS_TOP = 50;
    int END_FRAME_INSETS_LEFT  = 50;
    int END_FRAME_INSETS_BOTTOM = 0;
    int END_FRAME_INSETS_RIGHT = 50;
    int END_FRAME_WINDOWWIDTH = 400;
    int END_FRAME_WINDOWHEIGHT = 400;
    int FIRST_COLUMN = 0;
    int SECOND_COLUMN = 1;
    int THIRD_COLUMN = 2;
    int SCANWORDFRAME_BUTTON_WIDTH = 140;
    int SCANWORDFRAME_BUTTON_HEIGHT = 40;

    int SCANWORDFRAME_WIDTH = 800;
    int SCANWORDFRAME_HEIGHT = 300;
    int SCANWORDFRAME_FONTSIZE = 18;
    int SCANWORDFRAME_INSETS_TOP = 0;
    int SCANWORDFRAME_INSETS_LEFT  = 0;
    int SCANWORDFRAME_INSETS_BOTTOM = 10;
    int SCANWORD_INSETS_RIGHT = 1;

    int ADD_X = 100;
    int ADD_Y = 300;
    int ADD_WIDTH = 100;
    int ADD_HEIGHT = 50;

    int WORD_FIELD_X = 100;
    int WORD_FIELD_Y = 230;
    int WORD_FIELD_WIDTH = 300;
    int WORD_FIELD_HEIGHT = 40;

    int WORD_LABEL_X = 150;
    int WORD_LABEL_Y = 170;
    int WORD_LABEL_WIDTH = 150;
    int WORD_LABEL_HEIGHT = 100;

    int DESC_LABEL_X = 150;
    int DESC_LABEL_Y = 40;
    int DESC_LABEL_WIDTH = 150;
    int DESC_LABEL_HEIGHT = 100;

    int PLAY_BUTTON_X = 300;
    int PLAY_BUTTON_Y = 300;
    int PLAY_BUTTON_WIDTH = 100;
    int PLAY_BUTTON_HEIGHT = 50;

    int DESC_FIELD_X = 100;
    int DESC_FIELD_Y = 100;
    int DESC_FIELD_WIDTH = 300;
    int DESC_FIELD_HEIGHT = 100;

    int WORD_FIELD_FONT = 16;
    int DESC_FIELD_FONT = 18;

    int STARTFRAME_WIDTH = 500;
    int STARTFRAME_HEIGHT = 400;

}
